version: "3.9"
services:
  api:
    build:
        dockerfile: Dockerfile
        context: .
        target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
    redis:
        driver: local
